title:              ABC Blog
email:              junholee@gmail.com
description:        A Blog ABC
author:             JUNHO LEE
baseurl:            "/baseurl"
url:                "https://junho1ee.github.io/"

# Social Profiles
twitter_username:   abc
github_username:    junho1ee
facebook_username:  abc
instagram_username: abc 
linkedin_username:  abc

# Add your google-analytics ID here to activate google analytics
google_analytics:   #UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
